mysite02/account/urls.py
from django.conf.urls import url
from django.urls import path
from .import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
# from django.contrib.auth.views import LoginView       # 引入django的内置登录视图类
# from django.contrib.auth.views import LogoutView      # 引入django的内置OUT视图类
#
# from django.contrib.auth.views import PasswordChangeView
# from django.contrib.auth.views import PasswordChangeDoneView
# from django.contrib.auth.views import PasswordResetView
# from django.contrib.auth.views import PasswordResetConfirmView
# from django.contrib.auth.views import PasswordResetCompleteView
# from django.contrib.auth.views import PasswordResetDoneView

app_name = 'account'
urlpatterns = [
    # url(r'^login/$', views.user_login, name='user_login'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name="account/login.html"), name="user_login"),
    #以上是使用django的内置方法实现登录，并直接模板渲染，优点，1不用自己编写登录函数 2 可直接进行模板渲染 3 方便重定向

    #下面是使用django的内置方法实现退出
    # url(r'^logout/$',LogoutView.as_view(),name='user_logout'),   # LogoutView.as_view()将使用registration/logged_out.html
    url(r'^logout/$',auth_views.LogoutView.as_view(template_name='account/logout.html'),name='user_logout'),

    # 自定义的register view 实现注册
    url(r'^register/$', views.register, name="user_register"),

    # 使用内置方法实现密码Change
    url(r'^password-change/', auth_views.PasswordChangeView.as_view(
        template_name='account/password_change_form.html',
        success_url = reverse_lazy('account:password_change_done')),name='password_change'),   # 注意这个success_url

    url(r'^password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='account/password_change_done.html'), name='password_change_done'),

    # 使用内置方法实现密码Reset
    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='account/password_reset_form.html',
        email_template_name='account/password_reset_email.html',
        subject_template_name = 'account/password_reset_subject.txt',
        success_url=reverse_lazy('account:password_reset_done')),name='password_reset'),    # success_url='/account/password-reset-done/'
    path('password-reset-done/',auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html',
        success_url = reverse_lazy('account:password_reset_complete')),name='password_reset_confirm'),   # success_url='/account/password-reset-complete/'
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'),name='password_reset_complete'),


    # 用户个人信息展示url
    path('my-information/',views.myself,name='my_information'),
    # 用户个人信息编辑url
    path('edit-my-information/',views.myself_edit,name='edit_my_information'),
    # 用户个人图片信息的url
    path('my-image/',views.my_image,name='my_image')

]

mysite02/article/urls.py
from django.urls import path, re_path
from  . import views
from . import list_views


app_name = 'article'
urlpatterns = [
    path("article/", views.article_column, name="article_column"),
    path('rename-column/', views.rename_article_column, name="rename_article_column"),
    path('del-column/',views.del_article_column,name="del_article_column"),
    path('article-post/',views.article_post, name="article_post"),
    path("article-list/",views.article_list, name="article_list"),

    # reverse url路径，还带参数
    #re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),  # 这个坑，坑死我了
    path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name="article_detail"),

    path("del-article/", views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),

    # 具有分页功能的文章列表
    path("article-list-paginate/",views.article_list_paginate,name="article_list_paginate"),

    # 文章标题展示，任何用户都可访问
    path("list-article-titles/",list_views.article_title,name="list_article_titles"),

    # 通过单击上面文章的标题，可以查看文章详情
    path("list-article-detail/<int:id>/<slug:slug>/",list_views.article_detail,name="list_article_detail"),
    #path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name="article_content"),

    # 通过点击list-article-titles上的作者名称，可以列出该作者名下的所有article titles
    path("author_article_titles/<username>/",list_views.author_article_titles,name="author_article_titles"),

    # P168 为文章点赞的url
    path("like-article/",list_views.like_article,name="like_article"),


    # p196 添加标签tag信息,并在leftslider中添加该url的超链接
    path('article-tag/',views.article_tag,name="article_tag"),

    #p199 删除标签
    path("del-artcicle-tag",views.del_article_tag,name="del_article_tag"),


    ]

mysite02/blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.blog_title, name='blog_title'),
    path("", views.blog_title, name='blog_title'),
    # url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_detail'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),

]

mysite02/mysite02/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.views.generic import TemplateView   # 通用视图，用于制作home

urlpatterns = [
    path("home/",TemplateView.as_view(template_name="home.html"),name='home'),

    path('admin/', admin.site.urls),
    #url(r'^$', admin.site.urls),     # 设置根目录下的url
    url(r'^blog/', include('blog.urls', namespace='blog')),   # blog.urls这个点要特别注意，容易写成/
    url(r'^account/', include('account.urls', namespace='account')),

    path('article/',include('article.urls', namespace='article')),



]

mysite02/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

mysite02/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

mysite02/templates/header.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.hebau.edu.cn"><img src="{% static '/images/logo2.jpg' %}" width="100px"></a>
	    </div>

        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">HOME</a></li>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                <li><a href="{% url 'article:list_article_titles' %}">文章</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                    <li>
                        <div class="dropdown" style="margin-top:8px">
                            <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>
                                {{ user.username }}<span class='caret'></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                                <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                            </ul>
                        </div>
                    </li>

                    <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                    <li><a href="{% url 'account:user_register' %}">Sign up</a></li>

                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

mysite02/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home page{% endblock %}

{% block content %}
    <div class="text-center">
    <h1>WELCOM YOU</h1>
    <h3>Life is short. You need Python</h3>
    <h2>Django makes it easier to build better Web apps more quickly and with less
code.</h2>
    <img src="{% static 'images/bigdata1.png' %}">
</div>
{% endblock %}

mysite02/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page{{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>