mysite02/article/urls.py
from django.urls import path, re_path
from  . import views
from . import list_views


app_name = 'article'
urlpatterns = [
    path("article/", views.article_column, name="article_column"),
    path('rename-column/', views.rename_article_column, name="rename_article_column"),
    path('del-column/',views.del_article_column,name="del_article_column"),
    path('article-post/',views.article_post, name="article_post"),
    path("article-list/",views.article_list, name="article_list"),

    # reverse url路径，还带参数
    #re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),  # 这个坑，坑死我了
    path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name="article_detail"),

    path("del-article/", views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),

    # 具有分页功能的文章列表
    path("article-list-paginate/",views.article_list_paginate,name="article_list_paginate"),

    # 文章标题展示，任何用户都可访问
    path("list-article-titles/",list_views.article_title,name="list_article_titles"),

    # 通过单击上面文章的标题，可以查看文章详情
    path("list-article-detail/<int:id>/<slug:slug>/",list_views.article_detail,name="list_article_detail"),
    #path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name="article_content"),

    # 通过点击list-article-titles上的作者名称，可以列出该作者名下的所有article titles
    path("author_article_titles/<username>/",list_views.author_article_titles,name="author_article_titles"),

    # P168 为文章点赞的url
    path("like-article/",list_views.like_article,name="like_article"),


    # p196 添加标签tag信息,并在leftslider中添加该url的超链接
    path('article-tag/',views.article_tag,name="article_tag"),

    #p199 删除标签
    path("del-artcicle-tag",views.del_article_tag,name="del_article_tag"),


    ]

mysite02/blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.blog_title, name='blog_title'),
    path("", views.blog_title, name='blog_title'),
    # url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_detail'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),

]

mysite02/mysite02/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.views.generic import TemplateView   # 通用视图，用于制作home

urlpatterns = [
    path("home/",TemplateView.as_view(template_name="home.html"),name='home'),

    path('admin/', admin.site.urls),
    #url(r'^$', admin.site.urls),     # 设置根目录下的url
    url(r'^blog/', include('blog.urls', namespace='blog')),   # blog.urls这个点要特别注意，容易写成/
    url(r'^account/', include('account.urls', namespace='account')),

    path('article/',include('article.urls', namespace='article')),



]

mysite02/article/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)      # the column created time

    def __str__(self):
        return self.column



#++++++++++++++++文章标签数据模型++++++++++
# 注意：1 要写在ArticlePost的前面；2 要在ArticlePost()中加article_tag字段
class ArticleTag(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="tag")
    tag = models.CharField(max_length=300)
    def __str__(self):
        return self.tag




#++++++++++++++++发表文章的数据模型++++++++++
# Creat 文章Post的Modle
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from slugify import slugify
class ArticlePost(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    column = models.ForeignKey(ArticleColumn,on_delete=models.CASCADE,related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    # P167 Chap4.3 点赞功能
    users_like = models.ManyToManyField(User,related_name="articles_like",blank=True)
    # P195 Chap4.7.1 文章标签
    article_tag = models.ManyToManyField(ArticleTag,related_name="article_tag",blank=True)


    class Meta:
        ordering = ("title",)
        index_together = (("id","slug"),)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost,self).save(*args,**kwargs)

    # 获取链接地址中的id和slug，传给article.urls下的name=article_detail的url
    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id,self.slug])

    # 获取链接地址中的id和slug，传给article.urls下的name=list_article_detail的url
    def get_url_path(self):
        return reverse("article:list_article_detail",args=[self.id,self.slug])



# 创建评论Comment数据模型
from django.db import models
from django.contrib.auth.models import User
class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")
    commentator = models.CharField(max_length=30)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return "comment by {0} on {0}".format(self.commentator.username, self.article)    # 为啥要有.username呢？

mysite02/article/forms.py
from django import forms
from .models import ArticleColumn

#  创建文章标题表单
class AritcleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)


#  创建文章发布表单
from .models import ArticlePost
class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title","body")




# 创建评论表单类
from django import forms
from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator","body",)


# 创建文章标签表单类
from  .models import ArticleTag
class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ("tag",)

mysite02/article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from .models import ArticleColumn
from .forms import AritcleColumnForm

# Create your views here.
@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = AritcleColumnForm()
        return render(request,'article/column/article_column.html',{"columns":columns,"column_form":column_form})
    if request.method == 'POST':
        column_name = request.POST['column']       # get column_name from Ajax
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)    # check whether column_name is exist?
        if columns:
            return HttpResponse("2")     # if column_name already exist
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name)    # creat new item
            return HttpResponse("1")


# 编辑/重命名栏目名称
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST["column_id"]      #column_id = request.POST.get("column_id","default")
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


# 删除栏目
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]      # "column_id"是AJAX的Post传过来的data名
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

# 文章发布 view fun
# p200-201 重新添加文章标签功能
from .models import ArticlePost
from .forms import ArticlePostForm
import json
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method=="POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)    # title,body
                new_article.author = request.user   # author
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])  #column
                new_article.save()
                tags = request.POST['tags']          # tags
                if tags:
                    for atag in json.loads(tags):      # 不要忘记 import json
                        tag = request.user.tag.get(tag=atag)   # <==> tag = ArticleTag.objects.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    if request.method == 'GET':
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, "article/column/article_post.html",{"article_post_form":article_post_form,
                                                                   "article_columns":article_columns,
                                                                   "article_tags":article_tags,
                                                                   }
                      )


# 显示文章标题列表函数(同时可显示文章所属栏目的信息),
from .models import ArticlePost
@login_required(login_url="/account/login/")
def article_list(request):
    articles = ArticlePost.objects.filter(author=request.user)
    return render(request,"article/column/article_list.html",{"articles":articles})



# 显示文章详情，需要两个参数，文章的id和文章的slug
# 参考.models.ArticlePost(models.Model)中的get_absolute_url(self)
from django.shortcuts import  get_object_or_404
from .models import ArticlePost
from account.models import UserInfo
@login_required(login_url="/account/login/")
def article_detail(request,id,slug):
    article = get_object_or_404(ArticlePost,id=id,slug=slug)
    userinfo = UserInfo.objects.get(user=request.user)     # 用于显示作者图片
    return render(request,"article/column/article_detail.html",{"article":article,"userinfo":userinfo})



# 删除article函数---删除已经发表的article，必须是POST，参数为article的id
from .models import ArticlePost
@login_required(login_url="/account/login/")
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST["article_id"]
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

# 重新编辑article函数---重新编辑已经发表的aticle，GET时读取并显示article，POST时修改并提交article
from .models import ArticlePost
from .forms import ArticlePostForm
@login_required(login_url="/account/login/")
@csrf_exempt
def redit_article(request,article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title":article.title})
        this_article_column = article.column
        return render(request,"article/column/redit_article.html",{ "article_columns":article_columns,
                                                                    "article":article,
                                                                    "this_article_form":this_article_form,
                                                                    "this_article_column":this_article_column,
                                                                    }
                      )

    if request.method == "POST":
        this_redit_article = ArticlePost.objects.get(id=article_id)
        try:
            this_redit_article.column = request.user.article_column.get(id=request.POST["column_id"])
            this_redit_article.title = request.POST["title"]
            this_redit_article.body = request.POST["body"]
            this_redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")


# 重写article_list(),引入分页功能
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import ArticlePost
@login_required(login_url="/account/login/")
def article_list_paginate(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list,2)    #per_page=2,每页的项数
    page = request.GET.get("page")

    try:
        current_page = paginator.page(page)     # 正常读出请求页的页码，page必须>=1
    except PageNotAnInteger:
        current_page = paginator.page(1)        # 若请求的页码数值不是整数，则设定为第1页
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)    # 若请求的页码数值为空或没有page，则设定为总页数
    finally:
        articles = current_page.object_list      # 读出current_page下的所有article列表

    return render(request,"article/column/article_list_paginate.html",{"articles":articles,"page":current_page})


# 编写文章标签添加与显示的视图函数
from . models import ArticleTag
from . forms import ArticleTagForm
@login_required(login_url="/account/login/")
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request,'article/tag/tag_list.html',{"article_tags":article_tags,
                                                           "article_tag_form":article_tag_form
                                                           })
    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("The tag cannot be save")
        else:
            return HttpResponse("Sorry,the form is not valid!")

# 编写标签删除的视图函数
@login_required(login_url="/account/login/")
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

mysite02/templates/article/list/article_detail.html
{% extends "base.html" %}
{% load static %}
{#引入自定义标签article/templatetags/article_tags：#}
{#使用其中的latest_articles(n)显示最新发表文章#}
{#使用其中的@register.filter(name='markdown')模板选择器#}
{% load article_tags %}

{% block title %}{{ article.title }}{% endblock %}
{% block content %}
{% with total_likes=article.users_like.count   users_like=article.users_like.all %}
{#两个变量：total_like表示该文章的点赞数；users_like表示点赞该文章的所有用户列表#}

<div class="container">
    <div class="col-md-9">
{#    整个页面9:3，这里左边9的头部#}
        <header>
            <h1>{{ article.title}}</h1>
            <p>
                {#        为作者添加超链接，点击可查看该作者的全部article titles#}
                <a href="{% url 'article:author_article_titles' article.author.username %}">{{article.author.username  }}</a>
                {#            为文章添加点赞数#}
                <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-up">{{ total_likes }} like{{ total_likes | pluralize }}</span>
                {#            为文章添加浏览数#}
                <span style="margin-left:20px">{{ total_views }} view{{ total_views | pluralize }}</span>
            </p>
            <p>{{ article.created }}</p>
            {#    添加文章标签#}
            <p><span style="margin-right: 10px;"><strong>Tags:</strong></span>{{ article.article_tag.all | join:"," }}</p>
        </header>


        <!--Markdown display settings-->
        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.min.css' %}">
        <div id="editormd-view">
{#            <textarea id="append-test" style="display:none">{{ article.body }}</textarea>#}
{#            这里引入article_tags：中的自定义模板选择器markdown，代替上面的语句#}
            {{ article.body | markdown }}
        </div>
    {#++++++++++++++++++++++++++点赞功能部分(页面左边)+++++++++++++++#}
        <div>
            <p class="text-center">
                <a onclick="like_article({{ article.id }}, 'like')" href="#">
                    <span class="glyphicon glyphicon-thumbs-up">like</span>
                </a>
                <a onclick="like_article({{ article.id }},'unlike')" href="#">
                    <span style="margin-left:15px;" class="glyphicon glyphicon-thumbs-down">unlike</span>
                </a>
            </p>
        </div>
    {#+++++++++++++++++已点赞本文章的作者信息(页面左边)+++++++++++#}
        <div>
            <p class="text-center"><strong>点赞本文的读者</strong></p>
    {#      {% for user in article.users_like.all %}#}
            {% for user in users_like %}
                <p class="text-center">{{user.username}}</p>
            {% empty %}
                <p class="text-center">还没有人对此文章表态</p>
            {% endfor %}
        </div>
    {#+++++++++++++++++评论区(页面左边)+++++++++++#}
        <hr>
        <div>
            {# -----------------显示评论-----------#}
            <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有{{ comments.count }}评论</h3>
            {% for comment in article.comments.all %}
                <div>
                    <p><strong>{{ comment.commentator }}</strong>说:</p>
                    <p style="margin-left:40px;">{{ comment.body }}</p>
                </div>
            {% empty %}
                <p>没有评论</p>
            {% endfor %}
            {# -----------------编辑并提交评论-----------#}
            <h3><span class="glyphicon glyphicon-send"></span>看文章，发评论，不要沉默</h3>
            <form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">评论员</label>
                    <div class="col-sm-10">
                        {{ comment_form.commentator}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                    <div class="col-sm-10">
                        {{ comment_form.body }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <p><input type="submit" name="" value=" 发 评 论 " class="btn btn-primary"></p>
                    </div>
                </div>
            </form>
        </div>

    </div>

    {#++++++++++++++++++++++++++四个小辅助功能(页面右边)+++++++++++++++#}
    <div class="col-md-3">
        {#++++++++++++++++++++++1. 最受欢迎的文章top10(页面右边)+++++++++++++#}
        <p class="text-center"><h3>最受欢迎的文章</h3></p>
        <ol>
            {% for article_rank in most_viewed %}
            <li>
                <a href="{{article_rank.get_url_path}}">{{ article_rank.title }}</a>
            </li>
            {% endfor %}
        </ol>
        {#++++++++++++++++++++++2. 最新的文章top n(页面右边)+++++++++++++#}
        <hr>
        <p class="text-center"><h3>最新发表的文章</h3></p>
{#        调用自定义标签函数:article/templatetags/article_tags/latest_articles(n)#}
        {% latest_articles 4 %}

        {#++++++++++++++++++++++3. 最多评论的文章top5(页面右边)+++++++++++++#}
{#        调用自定义标签函数:article/templatetags/article_tags/most_commented_articles(n)#}
        <hr>
        <p class="text-center"><h3>最多评论的文章</h3></p>
        <ul>
            {% most_commented_articles as most_comments %}
            {% for article in most_comments %}
                <li>
                <a href="{{ article.get_url_path }}">{{ article.title }}</a>
                </li>
            {% endfor %}
        </ul>
        {#++++++++++++++++++++++4. 根据标签推荐与当前文章相似的文章(页面右边)+++++++++++++#}
        <hr>
        <p class="text-center"><h3>推荐相似的文章</h3></p>
        <ul>
            {% for similar in similar_articles %}
                <li>
                <a href="{{ similar.get_url_path }}">{{ similar.title }}</a>
                </li>
            {% empty %}
                <p>没有相似文章</p>
            {% endfor %}
        </ul>

    </div>


</div>

<!--Markdown display settings with scripts  and layer application-->
<script src='{% static "js/jquery.js" %}'></script>
<script src="{% static 'editor/lib/marked.min.js' %}"></script>
<script src="{% static 'editor/lib/prettify.min.js' %}"></script>
<script src="{% static 'editor/lib/raphael.min.js' %}"></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
<script src="{% static 'editor/editormd.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>

<script type="text/javascript">
    $(function () {
        editormd.markdownToHTML("editormd-view",{
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList:true,
            tex:true,
            flowChart:true,
            sequenceDiagram:true,
        });
    });

    {#点赞函数#}
    function like_article(id, action){
    $.ajax({
        url: "{% url 'article:like_article' %}",
        type: "POST",
        data: {"id":id, "action":action},
        success: function(e){
            if(e=="1"){
                layer.msg("感谢点赞!");
                {#sleep(1);#}
                {#停留1秒否则msg看不到#}
                window.location.reload();
            }else{
                layer.msg("我会继续努力！");
                {#sleep(1);#}
                window.location.reload();
            }
        },
    });
}


</script>


{% endwith %}
{% endblock %}

mysite02/templates/article/list/article_titles.html
{% extends "base.html" %}
{#引入自定义标签article/templatetags/article_tags,使用其中的total_articles函数显示文章总数#}
{% load article_tags %}
{% block title %}articles{% endblock %}
{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>书山有路勤为径，学海无涯苦作舟</h1>
        <p>这里有{% total_articles %}篇文章供你阅读</p>
    </div>
    <div class="container">
        {% for article in articles %}
            <div class="list-group">
            <!--为文章标题添加超链接，以获取该文章的id和slug-->
            <a href="{{ article.get_url_path }}" class="list-group-item active">
                <h4 class="list-group-item-heading">{{ article.title }}</h4>
            </a>
                <p class="list-group-item-text">作者：<a href="{% url 'article:author_article_titles' article.author.username %}">{{article.author.username  }}</a> </p>
                <p class="list-group-item-text">概要：{{ article.body|slice:"30"|linebreaks }}</p>

            </div>
        {% endfor %}

    {#    在下面引入paginator.html分页模板，因为发表的文章书目多了之后，需要分页#}
    {% include "paginator.html" %}
    </div>

{% endblock %}

mysite02/templates/article/list/author_article_titles.html
{% extends "base.html" %}
{% load static %}
{#引入自定义标签article/templatetags/article_tags,使用其中的author_total_articles函数显示该作者的文章总数#}
{% load article_tags %}

{% block title %}{{ user.username }}'s articles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>书山有路勤为径，学海无涯苦作舟</h1>
</div>

<div class="container">

    <div class="col-md-8">
        {% for article in articles %}
            <div class="list-group">
            <!--为文章标题添加超链接，以获取该文章的id和slug-->
            <a href="{{ article.get_url_path }}" class="list-group-item active">
                <h4 class="list-group-item-heading">{{ article.title }}</h4>
            </a>
                <p class="list-group-item-text">作者：<a href="{% url 'article:author_article_titles' article.author.username %}">{{article.author.username  }}</a> </p>
                <p class="list-group-item-text">概要：{{ article.body|slice:"30"|linebreaks }}</p>

            </div>
        {% endfor %}
        {#    在下面引入paginator.html分页模板，因为发表的文章书目多了之后，需要分页#}
        {% include "paginator.html" %}
    </div>

    <div class="col-md-4">
        <div>
            {% if userinfo.photo %}
                <img src="{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face" style="width: 300px">
            {% else %}
                <img name="user_face" src="{% static 'images/newton.jpg' %}" class="img-circle" id="my_photo" style="width: 300px">
            {% endif %}
        </div>
        <div>
            <p>{{ user.username }}</p>
{#            在作者的名字下面，添加一项内容：该作者发表的文章数量，#}
{#            引用的是自定义标签article/templatetages/article_tags下的函数#}
{#            注意：其中需要传一个user参数#}
            <p>共发表了{% author_total_articles  user %}篇文章</p>
            {% if userinfo %}
                <p>{{ userinfo.company }}</p>
                <p>{{ userinfo.aboutme }}</p>
            {% else %}
                <p>这个作者太懒了，什么也没有留下。</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

mysite02/templates/article/list/latest_articles.html
<ul>
    {% for  article in latest_articles %}
        <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
        </li>
    {% endfor %}

</ul>