mysite02/article/urls.py
from django.urls import path, re_path
from  . import views
from . import list_views


app_name = 'article'
urlpatterns = [
    path("article/", views.article_column, name="article_column"),
    path('rename-column/', views.rename_article_column, name="rename_article_column"),
    path('del-column/',views.del_article_column,name="del_article_column"),
    path('article-post/',views.article_post, name="article_post"),
    path("article-list/",views.article_list, name="article_list"),

    # reverse url路径，还带参数
    #re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),  # 这个坑，坑死我了
    path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name="article_detail"),

    path("del-article/", views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),

    # 具有分页功能的文章列表
    path("article-list-paginate/",views.article_list_paginate,name="article_list_paginate"),

    # 文章标题展示，任何用户都可访问
    path("list-article-titles/",list_views.article_title,name="list_article_titles"),

    # 通过单击上面文章的标题，可以查看文章详情
    path("list-article-detail/<int:id>/<slug:slug>/",list_views.article_detail,name="list_article_detail"),
    #path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name="article_content"),

    # 通过点击list-article-titles上的作者名称，可以列出该作者名下的所有article titles
    path("author_article_titles/<username>/",list_views.author_article_titles,name="author_article_titles"),

    # P168 为文章点赞的url
    path("like-article/",list_views.like_article,name="like_article"),


    # p196 添加标签tag信息,并在leftslider中添加该url的超链接
    path('article-tag/',views.article_tag,name="article_tag"),

    #p199 删除标签
    path("del-artcicle-tag",views.del_article_tag,name="del_article_tag"),


    ]

mysite02/blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.blog_title, name='blog_title'),
    path("", views.blog_title, name='blog_title'),
    # url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_detail'),
    path('<int:article_id>/', views.blog_article, name='blog_article'),

]

mysite02/mysite02/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.views.generic import TemplateView   # 通用视图，用于制作home

urlpatterns = [
    path("home/",TemplateView.as_view(template_name="home.html"),name='home'),

    path('admin/', admin.site.urls),
    #url(r'^$', admin.site.urls),     # 设置根目录下的url
    url(r'^blog/', include('blog.urls', namespace='blog')),   # blog.urls这个点要特别注意，容易写成/
    url(r'^account/', include('account.urls', namespace='account')),

    path('article/',include('article.urls', namespace='article')),



]

mysite02/article/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)      # the column created time

    def __str__(self):
        return self.column



#++++++++++++++++文章标签数据模型++++++++++
# 注意：1 要写在ArticlePost的前面；2 要在ArticlePost()中加article_tag字段
class ArticleTag(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="tag")
    tag = models.CharField(max_length=300)
    def __str__(self):
        return self.tag




#++++++++++++++++发表文章的数据模型++++++++++
# Creat 文章Post的Modle
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from slugify import slugify
class ArticlePost(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    column = models.ForeignKey(ArticleColumn,on_delete=models.CASCADE,related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    # P167 Chap4.3 点赞功能
    users_like = models.ManyToManyField(User,related_name="articles_like",blank=True)
    # P195 Chap4.7.1 文章标签
    article_tag = models.ManyToManyField(ArticleTag,related_name="article_tag",blank=True)


    class Meta:
        ordering = ("title",)
        index_together = (("id","slug"),)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost,self).save(*args,**kwargs)

    # 获取链接地址中的id和slug，传给article.urls下的name=article_detail的url
    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id,self.slug])

    # 获取链接地址中的id和slug，传给article.urls下的name=list_article_detail的url
    def get_url_path(self):
        return reverse("article:list_article_detail",args=[self.id,self.slug])



# 创建评论Comment数据模型
from django.db import models
from django.contrib.auth.models import User
class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")
    commentator = models.CharField(max_length=30)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return "comment by {0} on {0}".format(self.commentator.username, self.article)    # 为啥要有.username呢？

mysite02/article/forms.py
from django import forms
from .models import ArticleColumn

#  创建文章标题表单
class AritcleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)


#  创建文章发布表单
from .models import ArticlePost
class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title","body")




# 创建评论表单类
from django import forms
from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator","body",)


# 创建文章标签表单类
from  .models import ArticleTag
class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ("tag",)

mysite02/article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from .models import ArticleColumn
from .forms import AritcleColumnForm

# Create your views here.
@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = AritcleColumnForm()
        return render(request,'article/column/article_column.html',{"columns":columns,"column_form":column_form})
    if request.method == 'POST':
        column_name = request.POST['column']       # get column_name from Ajax
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)    # check whether column_name is exist?
        if columns:
            return HttpResponse("2")     # if column_name already exist
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name)    # creat new item
            return HttpResponse("1")


# 编辑/重命名栏目名称
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST["column_id"]      #column_id = request.POST.get("column_id","default")
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


# 删除栏目
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]      # "column_id"是AJAX的Post传过来的data名
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

# 文章发布 view fun
# p200-201 重新添加文章标签功能
from .models import ArticlePost
from .forms import ArticlePostForm
import json
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method=="POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)    # title,body
                new_article.author = request.user   # author
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])  #column
                new_article.save()
                tags = request.POST['tags']          # tags
                if tags:
                    for atag in json.loads(tags):      # 不要忘记 import json
                        tag = request.user.tag.get(tag=atag)   # <==> tag = ArticleTag.objects.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    if request.method == 'GET':
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, "article/column/article_post.html",{"article_post_form":article_post_form,
                                                                   "article_columns":article_columns,
                                                                   "article_tags":article_tags,
                                                                   }
                      )


# 显示文章标题列表函数(同时可显示文章所属栏目的信息),
from .models import ArticlePost
@login_required(login_url="/account/login/")
def article_list(request):
    articles = ArticlePost.objects.filter(author=request.user)
    return render(request,"article/column/article_list.html",{"articles":articles})



# 显示文章详情，需要两个参数，文章的id和文章的slug
# 参考.models.ArticlePost(models.Model)中的get_absolute_url(self)
from django.shortcuts import  get_object_or_404
from .models import ArticlePost
from account.models import UserInfo
@login_required(login_url="/account/login/")
def article_detail(request,id,slug):
    article = get_object_or_404(ArticlePost,id=id,slug=slug)
    userinfo = UserInfo.objects.get(user=request.user)     # 用于显示作者图片
    return render(request,"article/column/article_detail.html",{"article":article,"userinfo":userinfo})



# 删除article函数---删除已经发表的article，必须是POST，参数为article的id
from .models import ArticlePost
@login_required(login_url="/account/login/")
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST["article_id"]
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

# 重新编辑article函数---重新编辑已经发表的aticle，GET时读取并显示article，POST时修改并提交article
from .models import ArticlePost
from .forms import ArticlePostForm
@login_required(login_url="/account/login/")
@csrf_exempt
def redit_article(request,article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title":article.title})
        this_article_column = article.column
        return render(request,"article/column/redit_article.html",{ "article_columns":article_columns,
                                                                    "article":article,
                                                                    "this_article_form":this_article_form,
                                                                    "this_article_column":this_article_column,
                                                                    }
                      )

    if request.method == "POST":
        this_redit_article = ArticlePost.objects.get(id=article_id)
        try:
            this_redit_article.column = request.user.article_column.get(id=request.POST["column_id"])
            this_redit_article.title = request.POST["title"]
            this_redit_article.body = request.POST["body"]
            this_redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")


# 重写article_list(),引入分页功能
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import ArticlePost
@login_required(login_url="/account/login/")
def article_list_paginate(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list,2)    #per_page=2,每页的项数
    page = request.GET.get("page")

    try:
        current_page = paginator.page(page)     # 正常读出请求页的页码，page必须>=1
    except PageNotAnInteger:
        current_page = paginator.page(1)        # 若请求的页码数值不是整数，则设定为第1页
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)    # 若请求的页码数值为空或没有page，则设定为总页数
    finally:
        articles = current_page.object_list      # 读出current_page下的所有article列表

    return render(request,"article/column/article_list_paginate.html",{"articles":articles,"page":current_page})


# 编写文章标签添加与显示的视图函数
from . models import ArticleTag
from . forms import ArticleTagForm
@login_required(login_url="/account/login/")
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request,'article/tag/tag_list.html',{"article_tags":article_tags,
                                                           "article_tag_form":article_tag_form
                                                           })
    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("The tag cannot be save")
        else:
            return HttpResponse("Sorry,the form is not valid!")

# 编写标签删除的视图函数
@login_required(login_url="/account/login/")
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

mysite02/templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right"><!--button class="btn btn-primary">add column</button-->
        <button id= "add_column" onclick="add_column()" class="btn btn-primary"> add column</button>
    </p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        {% for line in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ line.column }}</td>
            <!--在下面td中添加两个功能按钮(编辑和删除)-->
            <!--点击相应条目(line)的按钮可以获取该条目的id，传给edit_column()和del_column()函数-->
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this, {{ line.id }})">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="del_column(this, {{ line.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了。</p>
        {% endfor %}
    </table>
</div>
<!--以下是3个JS函数，并通过layer窗口实现-->
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>

<script type="text/javascript">
{#<!--JS_fun1：添加栏目-->#}
        function add_column(){
            var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "新增栏目",
            content: '<div class="text-center" style="margin-top:20px"><p> 请输入新的栏目名称</p><p>{{ column_form.column }}</p></div > ',
            btn: ['确定', '取消'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: { "column": column_name },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("good");
                        } else {
                            layer.msg("此栏目已有，请更换名称")
                        }
                    },
                });
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        });
        }

{#<!--JS_fun2：编辑栏目-->#}
    function edit_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "编辑栏目",
            content: '<div class="text-center" style="margin-top:20px"> <p>请编辑的栏目名称</p><p><input type="text" id="new_name" value="'+name+'"></p> </div>',
            btn:['确定', '取消'],
            yes: function(index, layero){
                new_name = $("#new_name").val();
                $.ajax({
                    url: "{% url 'article:rename_article_column' %}",
                    type: "POST",
                    data: {"column_id": column_id, "column_name": new_name},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("good");
                        }else{
                            layer.msg("新的名称没有保存,修改失败。")
                        }
                    },
                });
            },
        });
    }



{#<!--JS_fun3：删除栏目-->#}
    function del_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除栏目",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article_column" %}',
                    type: "POST",
                    data: {"column_id":column_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }


</script>



{% endblock %}

mysite02/templates/article/column/article_detail.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}article detail{% endblock %}
{% block content %}
<div>
    <header>
        <h1>{{ article.title}}</h1>
        <!--<p>{{ article.author }}</p>-->
        <p>{{ user.username }}</p>
        <p>{{ article.created }}</p>
    </header>

     <div style="margin-right:100px">
            {% if userinfo.photo %}
            <img src="{{ userinfo.photo | striptags }}"class="img-circle" width="270px" id="my_photo" name="user_face">
            {% else %}
            <img src="{% static 'images/newton.jpg' %}" class="img-circle" width="270px" id="default_photo" name="user_face">
            {% endif %}
     </div>

    <!--Markdown display settings-->
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.min.css' %}">
    <div id="editormd-view">
        <textarea id="append-test" style="display:none">{{ article.body }}</textarea>
    </div>
</div>
    <!--Markdown display settings with scripts-->
    <script src='{% static "js/jquery.js" %}'></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src='{% static "editor/lib/underscore.min.js" %}'></script>
    <script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
    <script src='{% static "editor/lib/flowchart.min.js" %}'></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>

    <script type="text/javascript">
    $(function () {
        editormd.markdownToHTML("editormd-view",{
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList:true,
            tex:true,
            flowChart:true,
            sequenceDiagram:true,
        });
    });
    </script>
{% endblock %}

mysite02/templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}article list{% endblock %}
{% block content %}
<div>
    <table class="table table-hover">
        <tr>
            <td>文章序号</td>
            <td>文章标题</td>
            <td>所属栏目</td>
            <td>文章操作</td>
        </tr>
        <tr>
        {% for article in articles %}
            <td>{{ forloop.counter }}</td>
{#            <!--<td>{{ article.title }}</td>-->#}
            <!--为文章标题添加超链接，以获取该文章的id和slug-->
            <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>
{#                点击编辑图标后,会重新编辑aticle然后再提交，由于功能较复杂，所以编写视图函数并使用新的模板文件实现#}
                <a name="edit" href="{% url 'article:redit_article' article.id %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                </a>

{#                点击删除图标后,会执行JS_fun1的del_article()函数#}
                <a name="delete" href="javascript:" onclick="del_article(this, {{ article.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span>
                </a>

            </td>
        </tr>
        {% endfor %}
    </table>
</div>


<!--以下是1个JS函数，并通过layer窗口实现-->
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">

{#<!--JS_fun1： 删除文章-->#}
    function del_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type:"POST",
                    data: {"article_id":article_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }

</script>

{% endblock %}

mysite02/templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}article post{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

    <div style="margin-left:10px">
        <form class="form-horizontal" action="." method="post">{% csrf_token %}
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>标题：</span></div>
                <div class="col-md-10 text-left">{{article_post_form.title}}</div>
            </div>

            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>栏目：</span></div>
                <div class="col-md-10 text-left">
                    <select id="which_column">
                        {% for column in article_columns %}
                        <option value="{{column.id}}">{{column.column}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
{# +++++++++++++++++p200 栏目块下方添加文章标签块++++++++++++++#}
            <div class="row" style="margin-top:10px;">
                <div class="col-md-2 text-right"><span>标签：</span></div>
                <div class="col-md-10 text-left">
                    {% for tag in article_tags %}
                        <label class="checkbox-inline">
                        <input class="tagcheckbox" type="checkbox" id="{{ tag.id }}" name="article_tag" value="{{ tag.tag }}">
                        {{ tag.tag }}
                        </label>
                    {% empty %}
                        <p>You havenot any tag,Please <a href="{% url 'article:article_tag' %}"> add your tags</a></p>
                    {% endfor %}
                </div>
            </div>

{#        以下是文章内容块部分#}

            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>内容：</span></div>
                <!--<div class="col-md-10 text-left">{{article_post_form.body}}</div>-->
                <!--Start：使用Markdown插件美化编辑环境-->
                <div id="editormd" class="col-md-10 text-left">
                    <textarea style="display:none;" id="id_body"></textarea>
                </div>
                <!--End：使用Markdown插件美化编辑环境-->
                <!--Plus: 还需引入JS脚本，见该模板尾部-->
            </div>
            <div class="row">
                <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
            </div>
        </form>
    </div>

    <!--JS：使用Layer提交数据,  P201添加文章标签功能-->
    <script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
    <script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
    <script type="text/javascript">
        function publish_article(){
            var title = $("#id_title").val();
            var column_id = $("#which_column").val();
            var body = $("#id_body").val();
            var article_tags = [];
            $.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});
            $.ajax({
                url: "{% url 'article:article_post' %}",
                type: "POST",
                data: {"title":title, "body":body, "column_id":column_id,"tags":JSON.stringify(article_tags)},
                success: function(e){
                    if(e=="1"){
                        layer.msg("successful");
                        {#文章发布成功后，除了显示成功提示外，还要redirect到文章列表#}
                        location.href = "{% url 'article:article_list' %}";
                        {#或者也可以跳转到文章详情，article-detail但是详情页需要article的id和slug，比较麻烦#}

                    }else if(e=="2"){
                        layer.msg("sorry.") ;
                    }else{
                        layer.msg("项目名称必须写，不能空。");
                    }
                },
            });
        }
    </script>

    <!--JS：引入js脚本使用Markdown美化编辑环境-->
    <script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
    <script type="text/javascript">
        $(function() {
            var editor = editormd("editormd", {
                width : "100%",
                height : 640,
                syncScrolling : "single",
                path : "{% static 'editor/lib/' %}"
            });
        });
    </script>


{% endblock %}

mysite02/templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div class="container">
<div class="col-md-10">
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>文章标题:</span></div>
            <div class="col-md-10 text-left">{{this_article_form.title}}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>所属栏目:</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                        {% if column == this_article_column.column %}
                            <option value="{{column.id}}" selected="selected">{{column.column}} </option>
                        {% else %}
                            <option value="{{column.id}}">{{column.column}}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>文章内容:</span></div>
            <div id="editormd" class="col-md-10 text-left">
        <!--{{article_post_form.body}}-->
                <textarea style="display:none;" id="id_body">
{{article.body}}
                </textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="redit_article()">
        </div>
    </form>
</div>
</div>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
        $(function() {
        var editor = editormd("editormd", {
            width : "100%",
            height : 640,
            //syncScrolling : "single",
            path : "{% static 'editor/lib/' %}",
            });
        });

        function redit_article(){
            var title = $("#id_title").val();
            var column_id = $("#which_column").val();
            var body = $("#id_body").val();
            $.ajax({
                url: "{% url 'article:redit_article' article.id %}",
                type: "POST",
                data: {"title":title, "body":body, "column_id":column_id},
                success: function(e){
                    if(e=="1"){
                        layer.msg("successful");
                        location.href = "{% url 'article:article_list' %}";
                    }else{
                        layer.msg("sorry.");
                    }
                },
            });
        }

</script>

{% endblock %}